server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    # To start Consul in dev mode, use the following command: consul agent -node=learnmicro -dev
    # If port is occupied on Windows, use the following commands:
    # netstat -ano | findstr :<PORT>
    # taskkill /PID <PID> /F
    consul:
      enabled: true
      discovery:
        # Get list of the only healthy instances
        query-passing: true
        # Uncomment in order to disable the registration of the Gateway service
        # register: false
    gateway:
      routes:
        - id: multiplicator
          uri: lb://multiplicator/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
    default-filters:
      # In case of error, the request will be proxied to the next instance, since load balancer is enabled.
      # For cases if the Consul registry successfully checks the health of a given instance
      # and that one goes down immediately after
      - name: Retry
        args:
          retries: 3
          methods: GET,POST

# Uncomment the configuration below if you want to enable route matching logs
# logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace